### ISSUE TITLE
Remember puzzle type last used

### ISSUE THREAD

**Issue by ToastyKen** [cubing/timer#15]
Currently always defaults to 2x2.
Should instead remember last-used puzzle.
(Also should probably default to 3x3?)

**Comment by lgarron** [comment]
> Currently always defaults to 2x2.

This is actually for mobile testing. One of my devices takes a few seconds to initialize for 3x3x3.
I'll default to 3x3x3 when #1 is done (to avoid locking up the UI).

> Should instead remember last-used puzzle.

I agree, I just haven't gotten around to it. Thanks for filing!

**Comment by lgarron** [comment]
In order to keep things simple, I'm not going to implement this for the moment. However, the default puzzle type is now 3x3x3.

**Comment by lgarron** [comment]
This was `wontfix`, but turns out to be so simple to fix that it's kind of silly not to.

Maybe in the future we can revert to the default puzzle if it's been more than X minutes/hours since the last solve.
