### ISSUE TITLE
Change the favicon to match the theme.

### ISSUE THREAD

**Issue by lgarron** [cubing/timer#55]

**Comment by leyanlo** [comment]
Or just stop changing the theme and have it always be blue? Those other colors don't look as good.

**Comment by JoshHumpherys** [comment]
@leyanlo If you really want just blue then fork the repo and change line 83 of timerApp.js from `var themeColors = ["orange", "green", "red", "blue"];` to `var themeColors = ["blue"];`

**Comment by lgarron** [comment]
> Those other colors don't look as good.

I agree that blue looks better than the others, but I still like the changing colors. :-)
